### ISSUE TITLE
Update in global poker

### ISSUE THREAD

**Issue by nachishankar** [mr-feek/global-poker-hand-history-converter-chrome-extension#11] opened 2018-09-27 14:19 UTC
Hey Mr Feek, 
If you're the same group fpm5022 - there is a new update on global and the hand history converter doesn't work anymore. Is there any way you could fix it?

**Comment by billy49** [comment] 2018-09-27 16:10
+1, you would be my hero

**Comment by mr-feek** [comment] 2018-09-27 19:33
I don't play on global anymore, would someone else be willing to fix the markup / css?

The problem is probably here: https://github.com/mr-feek/global-poker-hand-history-converter-chrome-extension/blob/master/src/js/gp_override.js#L35

**Comment by nachishankar** [comment] 2018-09-27 21:00
I could try - but I have no idea how to code that well. It'll take me a while to figure it out. If you could walk me through the code once - I might be able to do it though

**Comment by chrisp200** [comment] 2018-09-27 22:09
I am pretty solid at css, but I'm lost in js.  if someone can tell which class is breaking this, I should be able to easily fix it.

**Comment by chrisp200** [comment] 2018-09-27 22:15
Someone can correct me if I'm wrong, but is the only issue that  historyDateContainer class isn't on the Global Poker HH page anymore?  Do we just need to replace $historyDateContainer.append(template); with 
$skin__cell q_c.append(template);

**Comment by nachishankar** [comment] 2018-09-28 05:40
I have no idea :|. I don't know what any of it even means

**Comment by CMaximus** [comment] 2018-09-28 21:41
Please fix

**Comment by mr-feek** [comment] 2018-09-28 22:03
https://github.com/mr-feek/global-poker-hand-history-converter-chrome-extension/pull/12

**Comment by mr-feek** [comment] 2018-10-14 19:26
this should be fixed now

**Closed as completed by mr-feek** 2018-10-14 19:26 UTC
